---
name: demo
run-name: ${{ github.actor }} is testing out Github Actions!
'on':
  push:
    branches:
      - master
jobs:
  main:
    name: Terraforming
    permissions:
      id-token: write # for OIDC
      contents: read # for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate into AWS
        uses: aws-actions/configure-aws-credentials/@v4
        with:
          role-to-assume: ${{ secrets.AWS_RoleToAssume }}
          aws-region: ${{ vars.AWS_Region }}
      
      - name: Install Repositary Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Initialise Terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_S3BUCKETNAME }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_DYNAMODBTABLENAME }}"
      
      - name: Applying Terraform
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve